### ISSUE TITLE
Support for SLO 

### ISSUE THREAD

**Issue by conanedogawa2** [felixrupp/user_cas#71] opened 2019-10-08 17:59 UTC
**Is your feature request related to a problem? Please describe.**
When i disconnect from another cassified application, Nextcloud is not disconnected.

**Describe the solution you'd like**
Make support for CAS SLO a thing for nextcloud without weird json service configuration.
https://apereo.github.io/cas/6.0.x/installation/Logout-Single-Signout.html 

Thanks !

**Comment by felixrupp** [comment] 2019-10-09 09:51
Hi @conanedogawa2

SingleLogout functionality is provided by apereos phpCAS library. I'm currently building up a testing environment to ensure the functionality of the library function, because I assume it’s not working as expected.

Please stand by.


Regards,
Felix

**Comment by felixrupp** [comment] 2019-10-22 07:26
Duplicate of #56

**Closed** 2019-10-22 07:27 UTC
Labels: bug
